### ISSUE TITLE
Build docs for Builder & Dazzle

### ISSUE THREAD

**Issue by ZanderBrown** [Valadoc/valadoc-org#121]
It would be good to add docs for Dazzle as it's use becomes more widespread in the GNOME community and possibly for Builder (libide) as well to ease plug-in development

**Comment by ZanderBrown** [comment]
Roughly when will this be deployed?

**Comment by btkostner** [comment]
@ZanderBrown https://valadoc.org/libide-1.0/index.htm

There seems to be an issue with the search though, so I'm still trying to figure that out.

**Comment by ZanderBrown** [comment]
Ping @chergert, thought you may be interested in this (they are you libraries)

**Comment by chergert** [comment]
Cool thanks for working on this. We should probably add a link in our developer docs once the kinks are worked out.

**Comment by benwaffle** [comment]
@btkostner  rebuild sphinx indexes?

**Comment by btkostner** [comment]
@benwaffle already have

**Comment by btkostner** [comment]
Forgot a build step to regen `searchd` config, search is working for those packages now.
