### ISSUE TITLE
No Node or npm version in package.json

### ISSUE THREAD

**Issue by curioussavage** [Valadoc/valadoc-org#131]
Hi, I was working on fixing the tooltips tonight but I can't get the darn app to install because npm fails for me on the install of the gulp dependency which is for some reason is pointing at github so npm tries to do a git checkout and fails because for some reason after it clones the project to /tmp there are changed files (pngs) I was wondering if the version of npm/node mattered. Will probably try a different version of the module but It would be nice to let people know what version is used.

**Comment by curioussavage** [comment]
I think you can get that version from the npm registry directly.

**Comment by curioussavage** [comment]
Look like I have perfect timing because they just released 4.0.0 hours ago. I will include an update to the package.json for that version in my tooltips patch.

**Comment by benwaffle** [comment]
It would be better to make a separate PR for the package.json update

**Comment by curioussavage** [comment]
I will make sure to keep them apart.

**Comment by benwaffle** [comment]
I made a PR to set the gulp version: #135

**Comment by curioussavage** [comment]
This could probably be closed right now. Still might not hurt to add the version of nodenpm you guys use though.

**Comment by benwaffle** [comment]
Doesn't this work on all modern versions of node?
