### ISSUE TITLE
valadoc 0.40 breaks API

### ISSUE THREAD

**Issue by benwaffle** [Valadoc/valadoc-org#144]
updates will be needed, probably just simple stuff
https://git.gnome.org/browse/vala/commit/?id=a8588da4c619abcafde892ffb9359e2c84d13eed
https://git.gnome.org/browse/vala/commit/?id=4e7c8d76cb13d99e219b68e03508bf435b3766f4

**Comment by ricotz** [comment]
Fixed with #162
