### ISSUE TITLE
URL for external search (for valadoc DuckDuckGo !bang support)

### ISSUE THREAD

**Issue by promi** [Valadoc/valadoc-org#145]
I would like to suggest a new [DuckDuckGo bang](https://duckduckgo.com/bang) for Valadoc, so I can just put something like "!valadoc Gtk.Entry" into my web browser search field.

The problem is that there does not seem to be any way to trigger the Valadoc search with an URL like for example:

https://valadoc.org/q=Gtk.Entry

DuckDuckGo needs a url in such a format:

Bang url, e.g. http://duckduckgo.com/?q={{{s}}}:
  Mark where the search goes with {{{s}}}

**Comment by lewisgoddard** [comment]
This would probably best be implemented at the end of [`data/scripts/valadoc.js`](https://github.com/Valadoc/valadoc-org/blob/master/data/scripts/valadoc.js), check for a GET parameter `q` and put it in the search box (UX) and trigger a search if it's present.

**Comment by lewisgoddard** [comment]
@promi This should now be present and is working for me: https://valadoc.org/?q=Gtk.Entry

**Comment by promi** [comment]
Works for me, too :).
