### ISSUE TITLE
GeoClue docs

### ISSUE THREAD

**Issue by danrabbit** [Valadoc/valadoc-org#155]
There are no docs for `GClue`. We need this to get developers onboard with using system location services instead of manually fetching locations

**Comment by benwaffle** [comment]
https://github.com/nemequ/vala-girs needs geoclue vapi

**Comment by tintou** [comment]
Vapi support added to geoclue ( https://gitlab.freedesktop.org/geoclue/geoclue/commit/6c7ae431eede9d4dfc84addb39327c3e342cc426 ) we only need the .vapi and .gir files to be added to the vala-girs repository before adding it to Valadoc itself

**Comment by tintou** [comment]
It's alive https://valadoc.org/libgeoclue-2.0/GClue.html
