### ISSUE TITLE
Gda out of date

### ISSUE THREAD

**Issue by ZanderBrown** [Valadoc/valadoc-org#169]
The docs for Gda seem outdated (the associated vapi was built with vapigen 0.28)

This is probably more an issue for vala-extra-vapis but i'm not sure where the upstream is for that these days

**Comment by benwaffle** [comment]
https://github.com/nemequ/vala-extra-vapis

**Comment by benwaffle** [comment]
unless it's built from a gir in which case, https://github.com/nemequ/vala-girs, although it has issues disabled

**Comment by ZanderBrown** [comment]
Looks like it's from built from gir then

Going upstream it looks like this might be a problem right up with Gda as the missing functions seem to have introspection `(skip)` attributes

**Comment by tintou** [comment]
Closing because it looks like it's not an issue with Valadoc
