### ISSUE TITLE
need guideline for self hosting valadoc

### ISSUE THREAD

**Issue by Readon** [Valadoc/valadoc-org#180]
I have tried to build this project, which works with slow engine.
I try to setup a virtual host on apache with the valadoc. 
However it always reports 404 when accessing the virtual host as http://xxxx.com/valadoc/.
It seems that the index.php does not found and processed by apache.
would you please provide some help on self hosting valadoc？

btw, I am living in some place where access to valadoc.org alway unstable and really slow, so that I have to host my own.

**Comment by ZanderBrown** [comment]
https://github.com/Valadoc/valadoc-org/blob/5b906254745d57e8571a72ae632d946690d75c91/package.json#L12

**Comment by Readon** [comment]
That is what I have done previously, it works. 
however it is slow, and the php is in single process, which always stall while switching page or searching.

**Comment by astavale** [comment]
Sounds like an Apache configuration question. The URL http://xxx.com/valadoc has the application running under the `valadoc` path so you want to try the Apache `Alias` directive in your `.conf` file. As a first attempt something like:

    <VirtualHost *:80>
    ServerName xxx.com
    DocumentRoot /srv/web/xxx
    ErrorLog /var/log/httpd/xxx.com_errors
    LogFormat combined
    TransferLog /var/log/httpd/xxx.com_access
    </VirtualHost>


    Alias /valadoc "/srv/web/valadoc.org"
    <Directory /srv/web/valadoc.org>
    Require all granted
    # AddHandler php5-script .php
    # AddHandler php7-script .php
    # AddHandler php-fastcgi-exec .php
    </Directory>

**Comment by Readon** [comment]
@astavale Thank you it is the problem of apache. I have config it well now.
However when i start searchd daemon and input search string in the input box, it repoort 500: Internal Server Error.
I have tested the searchd in standalone "php mode", is there any thing I should notice if i setup it on apache?

**Comment by astavale** [comment]
@Readon The first thing is to find what the error is. Look in `/var/log/httpd/xxx.com_errors` or however you've configured the log.

If your distribution is running journald then `journalctl -xe` may also give some clues. If your running SELinux take a look at `/var/log/audit/audit.log` as well.

It could be a number of problems:
 * file permissions
 * a package not installed
 * the PHP script isn't quite right for your local install

**Comment by Readon** [comment]
It works thank you all.
