### ISSUE TITLE
Broken link to glib unstable  C-Documentation 

### ISSUE THREAD

**Issue by peteruithoven** [Valadoc/valadoc-org#189]
https://valadoc.org/glib-2.0/index.htm points to https://developer.gnome.org/glib/unstable/ which seems to lacks a index.html (or something like that)

https://developer.gnome.org/glib/ lists versions, but it's 2.58.1 version is also broken.

What does work:
https://developer.gnome.org/glib/2.56/index.html

Should we reach out to gnome / glib?

**Comment by astavale** [comment]
Looks like unstable is back up, but it makes more sense for Valadoc,org to link to the stable version. Pull request updates that.
