### ISSUE TITLE
Gtk.TreeRowReference.free

### ISSUE THREAD

**Issue by cromerc** [Valadoc/valadoc-org#201]
Gtk.TreeRowReference.free is deprecated and should not be used according to:
https://developer.gnome.org/pygtk/stable/class-gtktreerowreference.html#method-gtktreerowreference--free

However the valadoc has no mention of it being deprecated, nor that it can cause crashes in our applications if used. I couldn't figure out for the life of me why my app kept crashing until I took a look at the gnome documentation instead of the vala documentation.
https://valadoc.org/gtk+-3.0/Gtk.TreeRowReference.free.html

**Comment by benwaffle** [comment]
Is that for GTK 2? Valadoc.org does not have GTK 2 documentation, only GTK 3. For python, the most up-to-date bindings are with [pygobject](https://pygobject.readthedocs.io/en/latest/).

**Comment by tintou** [comment]
Maybe PyGTK uses GTK+ 2 here because Gtk 3 hasn't deprecated this function according to the very latest documentation from the source: https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtktreemodel.c#L911

**Comment by ZanderBrown** [comment]
PyGTK only uses Gtk2 (and IIRC only works with Py2)
For Gtk3 you have to use PyGObject with Py2 or Py3
