### ISSUE TITLE
The inherited members box doesn't work with Epiphany

### ISSUE THREAD

**Issue by matzipan** [Valadoc/valadoc-org#23]
On [this](http://www.valadate.org:8000/#!api=dbus-glib-1/DBus.ObjectPath) page, the box which says "All known members inherited from class string" is not expandable in Epiphany. I'm not sure if it's the code faulty, or it's the fault of webkit2gtk.

**Comment by benwaffle** [comment]
Works On My Machine™ (arch linux and unmodified epiphany)

**Comment by matzipan** [comment]
Really?

**Comment by benwaffle** [comment]
right click > inspect element > console

are there any JS errors?

**Comment by matzipan** [comment]
TypeError: null is not an object (evaluating '/url[ \t]*\(('(.*)'|"(.*)")\)/.exec (style.backgroundImage)')

toggle_box — main.js:17

**Comment by btkostner** [comment]
@matzipan are you testing from master? It should have been fixed with this PR: https://github.com/flobrosch/valadoc-org/pull/59

**Comment by btkostner** [comment]
@matzipan can you check this again. Now that we have control over the domain, the site should be up-to-date with master.

**Comment by lewisgoddard** [comment]
The link https://valadoc.org/dbus-glib-1/DBus.ObjectPath shows this working as intended.
