### ISSUE TITLE
libide is empty

### ISSUE THREAD

**Issue by albfan** [Valadoc/valadoc-org#247]
I can generate locally with:

    valadoc --pkg gio-2.0 --pkg gtksourceview-4 /usr/share/gnome-builder/gir-1.0/Ide-3.32.gir -o valadoc

but https://valadoc.org/libide-1.0/index.htm is empty right now

**Comment by tintou** [comment]
It has been removed on-purpose as it is not a public library but an internal library to GNOME Builder so it shouldn't be in Valadoc (see https://github.com/Valadoc/valadoc-org/pull/218 )

**Comment by benwaffle** [comment]
I would argue that it's a public library, with the idea that people write external plugins against it for GNOME Builder.

**Comment by albfan** [comment]
@benwaffle I think so, But maybe this should be keep on gnome builder docs. It should be somewhere  public somehow.

**Comment by ZanderBrown** [comment]
Well we have gitg-ext and gedit which are similarly plugin api and considering there aren't really docs anywhere else having libide on Valadoc would be useful even for non-Vala devs

**Comment by tintou** [comment]
gedit has a public API, you can literally install it on every platform and create 3rd party plugins, it's not the case for libide, if anyone want to maintain a fork of valadoc somewhere for libide please feel free but we can't have all the statically linked libraries of every application inside of the official one.

**Comment by ZanderBrown** [comment]
> gedit has a public API, you can literally install it on every platform and create 3rd party plugins

Same for Builder? Really not seeing the difference here (other than installing gnome-builder-devel rather than gedit-devel)

**Comment by tintou** [comment]
The header files seems to only be available in Fedora, OpenMandriva and Mageia though and GNOME Builder is designed to be used using Flatpak anyway so it's not meant to be extended by 3rd part plugins

**Comment by ZanderBrown** [comment]
To a certain extent the same applies to gedit (not meant to be extended by 3rd party plugins) and when did someone last write a gitg plugin (did they ever?)

If you don't want to list more obscure/rare APIs we may as well remove hildon/clutter*/xcb* as well

**Comment by benwaffle** [comment]
@chergert could we get your opinion?

**Comment by chergert** [comment]
You can certainly extend it with 3rd party plugins, but it's not really something we encourage because we want people working upstream.
