### ISSUE TITLE
Search doesn't work from index.htm

### ISSUE THREAD

**Issue by danrabbit** [Valadoc/valadoc-org#32]
If you're at valadoc.org/ it works fine, but at /index.htm you get an error

`Query failed: (1064) sphinxql: syntax error, unexpected INDEX, expecting IDENT (or 49 other tokens) near 'index=2)'`

![screenshot from 2016-11-08 14 39 45](https://cloud.githubusercontent.com/assets/7277719/20120331/4a733ebe-a5c1-11e6-96db-1338c5bab8dc.png)

**Comment by lewisgoddard** [comment]
Query failed: (1064) sphinxql: syntax error, unexpected INDEX, expecting IDENT (or 49 other tokens) near 'index=2)'
