### ISSUE TITLE
Add a version field for documentation [$20]

### ISSUE THREAD

**Issue by danrabbit** [Valadoc/valadoc-org#4]
Something that would be useful (because of the nature of distros), is what package versions an API was last changed by. For example, someone just asked about gtk.stacksidebar and why it's not working in elementary OS. The reason is that it is new to gtk 3.16, and we ship gtk 3.14. If the docs said something like "since gtk 3.16" that would be awesome.
## 

[Bounty](https://www.bountysource.com/issues/38030667-add-a-version-field-for-documentation)

**Comment by danrabbit** [comment]
Copying Flo's comment from the old repo:

I agree. I already added proper version information to valac/vapigen/vapis as foundation. We only have to pick up the data and render it.

**Comment by tvale** [comment]
It seems to me this issue is fixed, can you confirm?
E.g. I can see:

> [ Version ( since = "3.16" ) ]
> public class StackSidebar : Bin, Implementor, Buildable

On the _Description_ section of https://valadoc.org/gtk+-3.0/Gtk.StackSidebar.html

**Comment by tintou** [comment]
Yeah I fixed this in Valadoc a while ago
