### ISSUE TITLE
Show deprecation information

### ISSUE THREAD

**Issue by matzipan** [Valadoc/valadoc-org#58]
Hey guys, so on [this page](https://lazka.github.io/pgi-docs/Gio-2.0/flags.html#Gio.FileMonitorFlags.SEND_MOVED), I can see some information like "Deprecated since 2.44: use Gio.FileMonitorFlags.WATCH_MOVES instead.", which is extremely useful. In valadoc.org, it's only displayed when you click [on the enum field](https://valadoc.org/gio-2.0/GLib.FileMonitorFlags.SEND_MOVED.html), but it's not displayed on the [main page](https://valadoc.org/gio-2.0/GLib.FileMonitorFlags.html). 

Dan says there's also supposed to be a strike-through style for deprecated items.

**Comment by btkostner** [comment]
Although not exactly the same, it's related to #4. I would assume these should be easy to impliment at the same time.

**Comment by btkostner** [comment]
Patch landed and deployed. https://valadoc.org/json-glib-1.0/Json.Object.add_member.html
