### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by danrabbit** [Valadoc/valadoc-org#6]
Should check with @flobrosch about the licensing and then make sure we add a license file

**Comment by lewisgoddard** [comment]
@danrabbit Can we harass flo about this? It's a little thing, but super important.

**Comment by danrabbit** [comment]
I shot him an email. If all else fails, it does look like a couple of the vala files have a LGPL 2.1 header so I would assume the rest of the code falls under that as well

**Comment by danrabbit** [comment]
Heard back from Florian and he says LGPL 2.1 the whole thing
