### ISSUE TITLE
Sphinx search index needs to be rebuilt

### ISSUE THREAD

**Issue by astavale** [Valadoc/valadoc-org#60]
It doesn't appear that the Sphinx search index is being rebuilt after each new documentation update. 

For example both gee-0.8 and libcolumbus have had documentation built in the last few weeks, but neither appear when entering relevant terms in search. Typing "ArrayList" does not return Gee.ArrayList. Also the tooltips for these libraries' documentation return "Query failed: (1064) no enabled local indexes to search". Whereas the tooltips for libraries that appear in search are fine. This suggests the newer documents have not been indexed. Ideally this would be done automatically.

**Comment by btkostner** [comment]
Sorry about that, there seems to be a problem with our deployment trying to index while serving. Should be fixed now.

**Comment by astavale** [comment]
I just wanted to compliment the team on a very fast and professional response. Thank you.
