### ISSUE TITLE
Minimum content width

### ISSUE THREAD

**Issue by btkostner** [Valadoc/valadoc-org#72]
Due to us centering the content area, sometimes when there is little content, the area will be super small.

![screenshot from 2017-02-15 14 43 43](https://cloud.githubusercontent.com/assets/3385679/22996838/649ea958-f38d-11e6-9a9c-fb9b6a715d5e.png)

**Comment by danrabbit** [comment]
Well if we want to eventually make the site responsive we probably don't want a minimum width, but we probably do want it to fill width up to the size of the viewport (or maxwidth, whichever is smaller)
